### ISSUE TITLE
Recipe overlap to princess mod

### ISSUE THREAD

**Issue by bell07** [Ezhh/abriglass#5]
The [abriglass:oneway_wall_pale](https://github.com/Ezhh/abriglass/blob/master/crafting.lua#L202)  uses the same recipe as [princess:princess_white_material](https://github.com/pithydon/princess/blob/master/init.lua#L482).
The princess mod was shortly before the abriglass so I ask you to change the recipe ;-)
My proposal is to use the new and mostly unused 'default:tin_lump' instead of 'default:clay_lump' for oneway_wall_pale and oneway_wall_dark

**Comment by Ezhh** [comment]
Thanks for raising this, but after reviewing the mod in question I'm unwilling to change for a number of reasons. I'll try to explain in full so you can understand my reluctance, and please accept my apologies if this isn't the response you were hoping for.

1. There's around 10+ servers using abriglass, and I do my best not to change any gameplay element of a mod once it has been adopted by any large servers (unless it's to improve security). It's not fun for players who stock piled a resource to make something, only to then find it's not what they need anymore.
2. princess seems to be a little known mod and I can find evidence of only one server using it, which appears to have very few players (0 online at the time of writing). This means the princess mod can change a recipe with much less disruption to server economy stability and lower risk of angry players.
3. The recipes were chosen very carefully with consideration for colour matching and what such a node might realistically be made of (from what's available in default). It's not really easy to give a good replacement recipe.
4. default:tin_lump doesn't exist on the servers abriglass was originally written for and it's not fair to expect a large server to rearrange its subgame over am obscure mod with low use. 

Finally, on a more personal note, the author of princess has previously reuploaded my work without attributing me and dropped the original license. They've also been known to delete mods they previously published on the MT forums (which breaks the rules of publishing there).  I don't want to change my mods to accommodate for a person who won't respect other mod authors and who removes availability of their work without warning. 

With that said, if you want to fork either princess or abriglass for your own use and change a recipe in your fork so they work together, I'll be happy to help with anything needed (though from what I've seen of your work, you won't need it).

**Comment by bell07** [comment]
Thanks for detailed explanation and background informations. 
I know the adoption for recipes is usually the task for subgame developer and this issue related only to subgames used both of the mods (expected count 0 at the time, maybe 1 comming soon ;=) so I am not disappointing with your decision.
How did you checked the servers for mods for 1 and 2?
I try to propose the recipe change to the princess mod, if not accepted I just change them in my WIP subgame

**Comment by Ezhh** [comment]
Check http://servers.minetest.net/list and CRTL+F. You should note this isn't foolproof; servers that have been running for a length of time will sometimes stop announcing their mods and some servers are of course not listed. I pay enough attention to my own mods to know it's about ten servers total using abriglass. princess may have more than 1, but 1 is all that displays it on the list right now.

It's good to hear someone else is working on subgames too. I just this morning spent some time groaning that all commonly used inventory mods require default in depends... and default won't exist in the game I'm working on. I also plan to create a separate version of abriglass for use in my own subgame due to this, so I know some of the challenges.

Feel free to let me know if you need help adapting any of my mods - more than happy to see them used. :)

**Comment by bell07** [comment]
> I just this morning spent some time groaning that all commonly used inventory mods require default in depends...

`<advertising>`my smart_inventory uses default optional only. I grepped it now, "default_furnace_front.png" for cooking recipe preview (i will replace), and experimental workbench mode uses some of default stuff.  But the mod should work without default without issues. It is on my roadmap to drop set default dependency optional only`</advertising> `
smart_inventory used on servers = 0 :-(

**Comment by Ezhh** [comment]
Have already been taking a look. ;)  I'm hoping to keep it simple and would ideally work with sfinv, but it's far from decided. 

I'm a bit of a perfectionist with my formspecs and get twitchy if everything doesn't line up perfectly, so don't be surprised if you see me with an issue or two if I test it out.

**Comment by bell07** [comment]
smart_inventory uses own item- and recipe caches so it is may oversized for some use cases, but I like it as is. The "crafting page" is most powerful with focus to support player in survuval, developed for my needs ;-).
Agree the sfinv is the best choice for KiSS inventory. 

```
 $ fgrep -R default .
./api.lua:local theme_main = "bgcolor[#080808BB;true]" .. default.gui_bg ..
./api.lua:		default.gui_bg_img
./api.lua:local theme_inv = default.gui_slots .. [[
./depends.txt:default
```
So you can just fork them, replace or remove the default backgrounds, and replace the gui_slots string (still commented out in code) so you can remove the default dependency.

**Comment by Ezhh** [comment]
That's what I'm thinking :)
